# Generated by Django 6.0.6 on 2026-07-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blogreaction',
            name='unique_blog_reaction',
        ),
        migrations.RemoveField(
            model_name='blogview',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogview',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_bookmark',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='commentreaction',
            name='unique_comment_reaction',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.RemoveField(
            model_name='blogreaction',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogreaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogView',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogReaction',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReaction',
        ),
    ]
